In [ ]:
def fun(x:str, y:float = 6.5)->int:
  x = float(x)
  return x+y
value = fun('3')
print(value)

9.5


In [ ]:
!pip install spacy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip show spacy

Name: spacy
Version: 3.4.1
Summary: Industrial-strength Natural Language Processing (NLP) in Python
Home-page: https://spacy.io
Author: Explosion
Author-email: contact@explosion.ai
License: MIT
Location: /usr/local/lib/python3.7/dist-packages
Requires: pydantic, cymem, spacy-loggers, catalogue, tqdm, thinc, srsly, typing-extensions, requests, typer, pathy, langcodes, spacy-legacy, preshed, setuptools, packaging, jinja2, wasabi, murmurhash, numpy
Required-by: fastai, en-core-web-sm


In [ ]:
!python -m spacy download en_core_web_sm

2022-09-05 04:07:33.385539: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 12.8 MB 6.9 MB/s 
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


In [ ]:
import spacy
spacy_en = spacy.load('en_core_web_sm')
text = "David's book wasn't famous, but his family loved his book."
for token in spacy_en.tokenizer(text):
  print(token)

David
's
book
was
n't
famous
,
but
his
family
loved
his
book
.


In [ ]:
from nltk.tokenize import TweetTokenizer
tweet = u"Snow White and the Seven Degrees #MakeAMovieCold@midnight:-)"
tokenizer = TweetTokenizer()
print(tokenizer.tokenize(tweet.lower()))

['snow', 'white', 'and', 'the', 'seven', 'degrees', '#makeamoviecold', '@midnight', ':-)']


In [ ]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
print(word_tokenize("Snow White and the Seven Degrees #MakeAMovieCold@midnight:-)"))

['Snow', 'White', 'and', 'the', 'Seven', 'Degrees', '#', 'MakeAMovieCold', '@', 'midnight', ':', '-', ')']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
from nltk.tokenize import word_tokenize, WordPunctTokenizer, TreebankWordTokenizer, RegexpTokenizer, sent_tokenize

text = """
Have you ever fallen head.
over heels for somebody.
Not just somebody.
No no.
Rex you did it again.
Have you ever fallen head.
over heels for somebody.
That made promises.
to give you the world Um.
I really hope they held you down.
I really hope it was no lying.
Cause when heart breaks it.
feel like the world's gone.
But if the love's real.
"""

print(word_tokenize(text))
print(WordPunctTokenizer().tokenize(text))
print(TreebankWordTokenizer().tokenize(text))
print(RegexpTokenizer('\w+').tokenize(text))
print(sent_tokenize(text))

['Have', 'you', 'ever', 'fallen', 'head', '.', 'over', 'heels', 'for', 'somebody', '.', 'Not', 'just', 'somebody', '.', 'No', 'no', '.', 'Rex', 'you', 'did', 'it', 'again', '.', 'Have', 'you', 'ever', 'fallen', 'head', '.', 'over', 'heels', 'for', 'somebody', '.', 'That', 'made', 'promises', '.', 'to', 'give', 'you', 'the', 'world', 'Um', '.', 'I', 'really', 'hope', 'they', 'held', 'you', 'down', '.', 'I', 'really', 'hope', 'it', 'was', 'no', 'lying', '.', 'Cause', 'when', 'heart', 'breaks', 'it', '.', 'feel', 'like', 'the', 'world', "'s", 'gone', '.', 'But', 'if', 'the', 'love', "'s", 'real', '.']
['Have', 'you', 'ever', 'fallen', 'head', '.', 'over', 'heels', 'for', 'somebody', '.', 'Not', 'just', 'somebody', '.', 'No', 'no', '.', 'Rex', 'you', 'did', 'it', 'again', '.', 'Have', 'you', 'ever', 'fallen', 'head', '.', 'over', 'heels', 'for', 'somebody', '.', 'That', 'made', 'promises', '.', 'to', 'give', 'you', 'the', 'world', 'Um', '.', 'I', 'really', 'hope', 'they', 'held', 'you', 'd

In [ ]:
from nltk import ngrams
sentence = 'There is no royal road to learning'
bigram = list(ngrams(sentence.split(), 2))
print(bigram)

[('There', 'is'), ('is', 'no'), ('no', 'royal'), ('royal', 'road'), ('road', 'to'), ('to', 'learning')]


In [ ]:
trigram = list(ngrams(sentence.split(), 3))
print(trigram)

[('There', 'is', 'no'), ('is', 'no', 'royal'), ('no', 'royal', 'road'), ('royal', 'road', 'to'), ('road', 'to', 'learning')]


In [ ]:
def n_grams(text,n):
    '''
    takes tokens or text, returns a list of n-grams
    '''
    return [text[i:i+n] for i in range(len(text)-n+1)]

In [ ]:
cleaned = ["mary",",","n't","slap","green",'witch',"."]
print(n_grams(cleaned,3))

[['mary', ',', "n't"], [',', "n't", 'slap'], ["n't", 'slap', 'green'], ['slap', 'green', 'witch'], ['green', 'witch', '.']]


In [ ]:
from nltk.tokenize import word_tokenize 

# 아래의 불용어는 저자가 임의로 선정한 것으로 실제 의미있는 선정 기준이 아님
example = "고기를 아무렇게나 구우려고 하면 안 돼. 고기라고 다 같은 게 아니거든. 예컨대 삼겹살을 구울 때는 중요한 게 있지."
stop_words = "아무거나 아무렇게나 어찌하든지 같다 비슷하다 예컨대 이럴정도로 하면 아니거든"

stop_words = set(stop_words.split(" "))
word_tokens = word_tokenize(example)

print(stop_words)

result = [word for word in word_tokens if not word in stop_words]

print(word_tokens) 
print(result)

{'비슷하다', '이럴정도로', '어찌하든지', '아무거나', '하면', '예컨대', '같다', '아무렇게나', '아니거든'}
['고기를', '아무렇게나', '구우려고', '하면', '안', '돼', '.', '고기라고', '다', '같은', '게', '아니거든', '.', '예컨대', '삼겹살을', '구울', '때는', '중요한', '게', '있지', '.']
['고기를', '구우려고', '안', '돼', '.', '고기라고', '다', '같은', '게', '.', '삼겹살을', '구울', '때는', '중요한', '게', '있지', '.']


In [ ]:
ex = '1 2 3 4 5 6 7 8 9 10'
ex_t = set(ex.split(' '))
# ex_t = {1, 2, 3, 4, 5, 8, 10, 6, 7, 9}
# print(ex_t)
# for i in ex_t:
#   print(i)
sorted(ex_t)

['1', '10', '2', '3', '4', '5', '6', '7', '8', '9']

In [ ]:
def stemmer_f(idx):
  from nltk.stem import PorterStemmer
  stm = PorterStemmer()
  return stm.stem(idx)

In [ ]:
# from nltk.stem import PorterStemmer
# stemmer = PorterStemmer()

# print(stemmer('working'))

stemmer_f('working')

# print(stemmer.stem('working'),stemmer.stem('works'),stemmer.stem('worked'))
# print(stemmer.stem('amusing'),stemmer.stem('amuses'),stemmer.stem('amused'))
# print(stemmer.stem('happier'),stemmer.stem('happiest'))
# print(stemmer.stem('fancier'),stemmer.stem('fanciest'))
# print(stemmer.stem('was'), stemmer.stem('love'))

'work'

In [ ]:
from nltk.stem import LancasterStemmer
stemmer = LancasterStemmer()

print(stemmer.stem('working'),stemmer.stem('works'),stemmer.stem('worked'))
print(stemmer.stem('amusing'),stemmer.stem('amuses'),stemmer.stem('amused'))
print(stemmer.stem('happier'),stemmer.stem('happiest'))
print(stemmer.stem('fancier'),stemmer.stem('fanciest'))
print(stemmer.stem('was'), stemmer.stem('love'))

work work work
amus amus amus
happy happiest
fant fanciest
was lov


In [ ]:
from nltk.stem.regexp import RegexpStemmer
stm = RegexpStemmer('의')
print(stm.stem('의사'))
print(stm.stem('전문의사'))
print(stm.stem('전문의'))
print(stm.stem('시간의'))

사
전문사
전문
시간


In [ ]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('omw-1.4')
nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()
words = ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
print([lemmatizer.lemmatize(w) for w in words])

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


['policy', 'doing', 'organization', 'have', 'going', 'love', 'life', 'fly', 'dy', 'watched', 'ha', 'starting']


In [ ]:
import re
r = re.compile('ab{2,}c')

# r.search('ac')
# r.search('abc')
# r.search('abbc')
r.search('abbbbbbbbbbbbbbbbbbbc')

<re.Match object; span=(0, 21), match='abbbbbbbbbbbbbbbbbbbc'>

In [ ]:
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [ ]:
text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

In [ ]:
# 문장 토큰화
text = sent_tokenize(text)
print(text)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


In [ ]:
import nltk
nltk.download('stopwords')

#정제와 단어 토큰화
vocab = {} # 파이썬의 dictionary 자료형
sentences = []
stop_words = set(stopwords.words('english'))

for i in text:
    sentence = word_tokenize(i) # 단어 토큰화를 수행합니다.
    result = []

    for word in sentence: 
        word = word.lower() # 모든 단어를 소문자화하여 단어의 개수를 줄입니다.
        if word not in stop_words: # 단어 토큰화 된 결과에 대해서 불용어를 제거합니다.
            if len(word) > 2: # 단어 길이가 2이하인 경우에 대하여 추가로 단어를 제거합니다.
                result.append(word)
                if word not in vocab:
                    vocab[word] = 0 
                vocab[word] += 1
    sentences.append(result) 
print(sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
print(vocab)

{'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1}


In [ ]:
vocab_sorted = sorted(vocab.items(), key = lambda x:x[1], reverse = True)
print(vocab_sorted)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3), ('word', 2), ('keeping', 2), ('good', 1), ('knew', 1), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)]


In [ ]:
word_to_idx = {}
i = 0
for word, freq in vocab_sorted :
  if freq > 1:
    i = i+1
    word_to_idx[word] = i
print(word_to_idx)


{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


In [ ]:
vocab_size = 5
words_freq = [w for w, c in word_to_idx.items() if c>= vocab_size +1]
for w in words_freq:
  del word_to_idx[w]
print(word_to_idx)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [ ]:
word_to_idx['OOV'] = len(word_to_idx) + 1
print(len(word_to_idx))
print(word_to_idx['OOV'])

6
6


In [ ]:
encoded = []
for s in sentences:
  # print('s : ', s)
  temp = []
  for w in s:
    try:
      temp.append(word_to_idx[w])
    except KeyError:
      temp.append(word_to_idx['OOV'])
  encoded.append(temp)
print(encoded)

[[1, 5], [1, 6, 5], [1, 3, 5], [6, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [6, 6, 3, 2, 6, 1, 6], [1, 6, 3, 6]]


In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# np.concatenate((a,b), axis = 1)

AxisError: ignored

In [ ]:
c = np.array([[0, 1, 2], [3, 4, 5]])
d = np.array([[6, 7, 8], [9, 10, 11]])

np.concatenate((c, d), axis = 1)


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [ ]:
np.vstack([c,d])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.column_stack([c,d])

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [ ]:
cd = list(zip(c,d))
print(cd)

[(array([0, 1, 2]), array([6, 7, 8])), (array([3, 4, 5]), array([ 9, 10, 11]))]


In [ ]:
X, y = zip(['a', 1], ['b', 2], ['c', 3])
print(X, y)

('a', 'b', 'c') (1, 2, 3)


In [ ]:
list(zip(X,y))

[('a', 1), ('b', 2), ('c', 3)]

In [ ]:
from collections import Counter

In [ ]:
print(sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [ ]:
words = sum(sentences, [])
print(words)

['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge', 'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret', 'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept', 'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge', 'mountain']


In [ ]:
vocab = Counter(words)
print(vocab)

Counter({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1})


In [ ]:
vocab_size = 5
vocab = vocab.most_common(vocab_size)
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [ ]:
word_to_index = {}
i = 0
for (word, frequency) in vocab:
  i = i + 1
  word_to_index[word] = i
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [ ]:
!pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 19.4 MB 1.2 MB/s 
     |████████████████████████████████| 453 kB 55.2 MB/s 


In [ ]:
from konlpy.tag import Okt
okt = Okt()
print(okt.morphs("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))

['열심히', '코딩', '한', '당신', ',', '연휴', '에는', '여행', '을', '가봐요']


In [ ]:
print(okt.pos('열심히 코딩한 당신, 연휴에는 여행을 가봐요'))

[('열심히', 'Adverb'), ('코딩', 'Noun'), ('한', 'Josa'), ('당신', 'Noun'), (',', 'Punctuation'), ('연휴', 'Noun'), ('에는', 'Josa'), ('여행', 'Noun'), ('을', 'Josa'), ('가봐요', 'Verb')]


In [ ]:
print(okt.nouns('열심히 코딩한 당신, 연휴에는 여행을 가봐요'))

['코딩', '당신', '연휴', '여행']


In [ ]:
from konlpy.tag import Kkma  
kkma=Kkma()  
print(kkma.morphs("사과파이를 썬다"))

['사과', '파이', '를', '썰', 'ㄴ다']


In [ ]:
print(kkma.pos("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))  

[('열심히', 'MAG'), ('코딩', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETD'), ('당신', 'NP'), (',', 'SP'), ('연휴', 'NNG'), ('에', 'JKM'), ('는', 'JX'), ('여행', 'NNG'), ('을', 'JKO'), ('가보', 'VV'), ('아요', 'EFN')]


In [ ]:
!git clone https://github.com/SOMJANG/Mecab-ko-for-Google-Colab.git

Cloning into 'Mecab-ko-for-Google-Colab'...
remote: Enumerating objects: 115, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 115 (delta 11), reused 10 (delta 3), pack-reused 91
Receiving objects: 100% (115/115), 1.27 MiB | 14.14 MiB/s, done.
Resolving deltas: 100% (50/50), done.


In [ ]:
!bash /content/Mecab-ko-for-Google-Colab/install_mecab-ko_on_colab190912.sh

Installing konlpy.....
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Done
Installing mecab-0.996-ko-0.9.2.tar.gz.....
from https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
--2022-09-05 06:48:05--  https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
Resolving bitbucket.org (bitbucket.org)... 18.205.93.1, 18.205.93.2, 18.205.93.0, ...
Connecting to bitbucket.org (bitbucket.org)|18.205.93.1|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://bbuseruploads.s3.amazonaws.com/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz?response-content-disposition=attachment%3B%20filename%3D%22mecab-0.996-ko-0.9.2.tar.gz%22&response-content-encoding=None&AWSAccessKeyId=ASIA6KOSE3BNLWYRFWIO&Signature=6GPRqDBp19WudJb%2Bakduga4sRN4%3D&x-amz-security-token=FwoGZXIvYXdzEFgaDDE5HTOsszm9TVgDwSK%2BAc4zC3iJbDQEf0ZLWrGHb1s2Yl9Ry0kxZw%2Fq97NZRz6g64TeCUg6TY9qIjF9O8ubN49Q6

In [ ]:
from konlpy.tag import Mecab 
mecab = Mecab() 
text = u"""이제 구글 코랩에서 Mecab-ko라이브러리 사용이 가능합니다. 읽어주셔서 감사합니다.""" 
nouns = mecab.nouns(text) 
print(nouns)

['구글', '코', '랩', '라이브러리', '사용', '가능', '감사']


In [ ]:
from nltk.tokenize import sent_tokenize
from konlpy.tag import Hannanum
from konlpy.tag import Kkma
from konlpy.tag import Okt

hannanum = Hannanum()
kkma = Kkma()
okt = Okt()

#예시를 위해 영문장, 한문장을 임의로 설정합니다.
text1 = "I am graduate Yonsei university. My major is Bio Medical engineering. but my favorite is Machine learning&Data Science."
text2 = "자연어 처리. 어렵네요. 특히 한국어 처리는 더 어려운거 같아요. 다들 화이팅하세요!"

print("sent_tokenize를 사용하면 아래와 같이 토큰화됩니다.")
print(sent_tokenize(text1))
print(sent_tokenize(text2))

print("Hannanum을 쓰면 아래와 같이 분류됩니다.")
print(hannanum.morphs(text1))
print(hannanum.morphs(text2))

print("Kkma를 쓰면 아래와 같이 분류됩니다.")
print(kkma.morphs(text1))
print(kkma.morphs(text2))

print("Okt를 사용하면 아래와 같이 분류됩니다.")
print(okt.morphs(text1))
print(okt.morphs(text2))

#jpype._jvmfinder.JVMNotFoundException: No JVM shared library file (jng>vm.dll) found. Try setting up the JAVA_HOME environment variable properly.
#라는 오류가 발생하신다면 C:\아나콘다설치위치\Lib\site-packages\jpype 에 들어가서 _jvmfinder.py 파일을 여신 다음 ctrl + F 로 java_home 검색 후
#java_home = "자바설치경로" 로 해주시면 오류없이 실행됩니다.

sent_tokenize를 사용하면 아래와 같이 토큰화됩니다.
['I am graduate Yonsei university.', 'My major is Bio Medical engineering.', 'but my favorite is Machine learning&Data Science.']
['자연어 처리.', '어렵네요.', '특히 한국어 처리는 더 어려운거 같아요.', '다들 화이팅하세요!']
Hannanum을 쓰면 아래와 같이 분류됩니다.
['I', 'am', 'graduate', 'Yonsei', 'university', '.', 'My', 'major', 'is', 'Bio', 'Medical', 'engineering', '.', 'but', 'my', 'favorite', 'is', 'Machine', 'learning&Data', 'Science', '.']
['자연어', '처리', '.', '어렵', '네', '요', '.', '특히', '한국어', '처리', '는', '더', '어려운거', '같', '아', '요', '.', '다들', '화이팅하세요', '!']
Kkma를 쓰면 아래와 같이 분류됩니다.
['I', 'am', 'graduate', 'Yonsei', 'university', '.', 'My', 'major', 'is', 'Bio', 'Medical', 'engineering', '.', 'but', 'my', 'favorite', 'is', 'Machine', 'learning', '&', 'Data', 'Science', '.']
['자연어', '처리', '.', '어렵', '네요', '.', '특히', '한국어', '처리', '는', '더', '어렵', 'ㄴ', '거', '같', '아요', '.', '다', '들', 'ㄹ', '화이팅하세', '요', '!']
Okt를 사용하면 아래와 같이 분류됩니다.
['I', 'am', 'graduate', 'Yonsei', 'university', '.', 'My', 'major', '

In [ ]:
import urllib.request
import time
from konlpy.tag import Okt
from konlpy.tag import Komoran
from konlpy.tag import Kkma
import matplotlib.pyplot as plt

urllib.request.urlretrieve("https://raw.githubusercontent.com/e9t/nsmc/master/ratings.txt", filename="ratings.txt")


def set_review_data(file_nm):
    with open(file_nm, "r", encoding="utf8") as f:
        data = [line.split('\t') for line in f.read().splitlines()]
    return data[1:20001]


start_time = time.time()
print('[BEGIN] 리뷰 데이터를 읽는다.')
review_data = set_review_data('ratings.txt')
print('review_data size->', len(review_data))
print('[END] 리뷰 데이터를 읽는다. (', time.time() - start_time, ')sec')

[BEGIN] 리뷰 데이터를 읽는다.
review_data size-> 20000
[END] 리뷰 데이터를 읽는다. ( 1.618776798248291 )sec


In [ ]:
kolnpy_perform = {}
print(review_data[1][1])

디자인을 배우는 학생으로, 외국디자이너와 그들이 일군 전통을 통해 발전해가는 문화산업이 부러웠는데. 사실 우리나라에서도 그 어려운시절에 끝까지 열정을 지킨 노라노 같은 전통이있어 저와 같은 사람들이 꿈을 꾸고 이뤄나갈 수 있다는 것에 감사합니다.


In [ ]:
start_time = time.time()
kkma = Kkma()
nouns = [kkma.nouns(datas[1]) for datas in review_data]
print(nouns[1])
kolnpy_perform['kkma'] = time.time() - start_time
print('꼬꼬마 명사 추출 (', kolnpy_perform['kkma'], ')sec')